"""Rename department to departments

Revision ID: 94e9f2b7064b
Revises: e9d7be69ff6b
Create Date: 2025-04-08 21:22:47.647391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94e9f2b7064b'
down_revision = 'e9d7be69ff6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
